### ISSUE TITLE
Support rebuilding against multiple new packages

### ISSUE THREAD

**Issue by zhsj** [Debian/ratt#13]
The user case is, some packages should be bumped up version together.
For example,  I want to bump up golang-github-azure-azure-sdk-for-go, but it requires bump up golang-github-azure-go-autorest too.
If I just test golang-github-azure-go-autorest first, some packages fail, because of the incompatible of old golang-github-azure-azure-sdk-for-go and new  golang-github-azure-go-autorest.That causes a lot noise.
So I hope ratt can support rebuilding multiple packages.

**Comment by stapelberg** [comment]
Yeah, I ran into this a while ago, too. Pull requests welcome :)
