### ISSUE TITLE
'go get' for installing executables is deprectated

### ISSUE THREAD

**Issue by simevo** [Debian/ratt#23]
following the instructions in the README on debian sid with go1.18.4, `go get -u github.com/Debian/ratt` returns:

```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by stapelberg** [comment]
I’m not maintaining ratt anymore (see also https://michael.stapelberg.ch/posts/2019-03-10-debian-winding-down/), but I pushed a fix that declares a Go module, so at least we should be in a good state regarding the Go environment now.
