### ISSUE TITLE
find reverse dependencies for distributions other then unstable

### ISSUE THREAD

**Issue by brianmay** [Debian/ratt#6]
Sometimes I would like to be able to find all reverse dependencies, say from wheezy, and rebuild them.

AFAIK Currently you can rebuild packages on wheezy, but this will cause errors if unstable has more packages then what was available on wheezy.

**Comment by stapelberg** [comment]
Have you tried just string-replacing “sid” and “unstable” with “wheezy” in ratt.go? Does that work? If not, what goes wrong?

Also, do you have an example I could use to reproduce the issue you’re mentioning?

**Comment by brianmay** [comment]
I tried it on Jessie and it didn't work.

However I think that is because apt-get on Jessie doesn't have the "apt-get indextargets" command, and the fallback didn't work. /var/lib/apt/lists/*_InRelease doesn't get downloaded for a distribution just because the sources are referenced, it appears.

So now I have upgraded to testing, I really should try it again.

The package in question was libav - I did a security update for it for wheezy and want to know what packages in wheezy will break if I convince the security-team to include it. So as I result I need to be confident I am including all the relevant packages.

**Comment by brianmay** [comment]
For some reason the following command produces no results, not sure why:

```
"dose-ceve" "--deb-native-arch=amd64" "-T" "deb" "-r" "libav-tools,libav-dbg,libav-doc,libavutil54,libavcodec56,libavdevice55,libavformat56,libavfilter5,libswscale3,libavutil-dev,libavcodec-dev,libavdevice-dev,libavformat-dev,libavfilter-dev,libswscale-dev,libavresample-dev,libavresample2,libavcodec-extra-56,libavcodec-extra" "-G" "pkg" "debsrc:///var/lib/apt/lists/ftp.au.debian.org_debian_dists_wheezy_main_source_Sources" "debsrc:///var/lib/apt/lists/ftp.au.debian.org_debian_dists_wheezy_contrib_source_Sources" "debsrc:///var/lib/apt/lists/ftp.au.debian.org_debian_dists_wheezy_non-free_source_Sources"
```

**Comment by brianmay** [comment]
So it looks like I need to download the binary package indexes, not just the source indexes for this to work.

However just noticed that the --extra-package= flag to sbuild doesn't appear to be working. So while it is building the required packages, it is building against the libav that is already in wheezy, not my new version :-(

**Comment by brianmay** [comment]
I submitted http://bugs.debian.org/820882 on this problem.

**Comment by brianmay** [comment]
ratt needs to make sure that when it uses the same architecture for building the packages as in the source *.changes file. e.g. if the *.changes is i386, we need to use an i386 chroot. Otherwise it won't work. Still not entirely sure I understand in my case why it chose amd64 as the default, so will think about this and open up a new issue if required.
