### ISSUE TITLE
diff build package against archive version

### ISSUE THREAD

**Issue by jspricke** [Debian/ratt#7]
What about optionally diffing the generated packages against the version in the archive, so we can detect needed rebuilds as well? Useful tools would be:
* diffoscope
* abipkgdiff
* Pkg-ABIdiff (not yet in Debian)

I could work in this, it it's wanted.

**Comment by stapelberg** [comment]
Thanks for starting this discussion. Unfortunately, I don’t quite follow what the use-case is. Could you describe in more detail, perhaps with an example please?

**Comment by jspricke** [comment]
I maintain a couple of packages that may need to be recompiled once
their build dependencies are updated. So it would be great to diff the
generated package and get a list of packages that need a version bump.

Thinking of it, maybe it would be easier to simply write a script to do
the download and diff afterwards. So feel free to close this.
